namespace ReactWithDotNet;

partial class Style
{
    public string accentColor { get; set; }
    public string additiveSymbols { get; set; }
    public string alignContent { get; set; }
    public string alignItems { get; set; }
    public string alignSelf { get; set; }
    public string alignmentBaseline { get; set; }
    public string all { get; set; }
    public string animation { get; set; }
    public string animationComposition { get; set; }
    public string animationDelay { get; set; }
    public string animationDirection { get; set; }
    public string animationDuration { get; set; }
    public string animationFillMode { get; set; }
    public string animationIterationCount { get; set; }
    public string animationName { get; set; }
    public string animationPlayState { get; set; }
    public string animationRange { get; set; }
    public string animationRangeEnd { get; set; }
    public string animationRangeStart { get; set; }
    public string animationTimeline { get; set; }
    public string animationTimingFunction { get; set; }
    public string appRegion { get; set; }
    public string appearance { get; set; }
    public string ascentOverride { get; set; }
    public string aspectRatio { get; set; }
    public string backdropFilter { get; set; }
    public string backfaceVisibility { get; set; }
    public string background { get; set; }
    public string backgroundAttachment { get; set; }
    public string backgroundBlendMode { get; set; }
    public string backgroundClip { get; set; }
    public string backgroundColor { get; set; }
    public string backgroundImage { get; set; }
    public string backgroundOrigin { get; set; }
    public string backgroundPosition { get; set; }
    public string backgroundPositionX { get; set; }
    public string backgroundPositionY { get; set; }
    public string backgroundRepeat { get; set; }
    public string backgroundRepeatX { get; set; }
    public string backgroundRepeatY { get; set; }
    public string backgroundSize { get; set; }
    public string basePalette { get; set; }
    public string baselineShift { get; set; }
    public string baselineSource { get; set; }
    public string blockSize { get; set; }
    public string border { get; set; }
    public string borderBlock { get; set; }
    public string borderBlockColor { get; set; }
    public string borderBlockEnd { get; set; }
    public string borderBlockEndColor { get; set; }
    public string borderBlockEndStyle { get; set; }
    public string borderBlockEndWidth { get; set; }
    public string borderBlockStart { get; set; }
    public string borderBlockStartColor { get; set; }
    public string borderBlockStartStyle { get; set; }
    public string borderBlockStartWidth { get; set; }
    public string borderBlockStyle { get; set; }
    public string borderBlockWidth { get; set; }
    public string borderBottom { get; set; }
    public string borderBottomColor { get; set; }
    public string borderBottomLeftRadius { get; set; }
    public string borderBottomRightRadius { get; set; }
    public string borderBottomStyle { get; set; }
    public string borderBottomWidth { get; set; }
    public string borderCollapse { get; set; }
    public string borderColor { get; set; }
    public string borderEndEndRadius { get; set; }
    public string borderEndStartRadius { get; set; }
    public string borderImage { get; set; }
    public string borderImageOutset { get; set; }
    public string borderImageRepeat { get; set; }
    public string borderImageSlice { get; set; }
    public string borderImageSource { get; set; }
    public string borderImageWidth { get; set; }
    public string borderInline { get; set; }
    public string borderInlineColor { get; set; }
    public string borderInlineEnd { get; set; }
    public string borderInlineEndColor { get; set; }
    public string borderInlineEndStyle { get; set; }
    public string borderInlineEndWidth { get; set; }
    public string borderInlineStart { get; set; }
    public string borderInlineStartColor { get; set; }
    public string borderInlineStartStyle { get; set; }
    public string borderInlineStartWidth { get; set; }
    public string borderInlineStyle { get; set; }
    public string borderInlineWidth { get; set; }
    public string borderLeft { get; set; }
    public string borderLeftColor { get; set; }
    public string borderLeftStyle { get; set; }
    public string borderLeftWidth { get; set; }
    public string borderRadius { get; set; }
    public string borderRight { get; set; }
    public string borderRightColor { get; set; }
    public string borderRightStyle { get; set; }
    public string borderRightWidth { get; set; }
    public string borderSpacing { get; set; }
    public string borderStartEndRadius { get; set; }
    public string borderStartStartRadius { get; set; }
    public string borderStyle { get; set; }
    public string borderTop { get; set; }
    public string borderTopColor { get; set; }
    public string borderTopLeftRadius { get; set; }
    public string borderTopRightRadius { get; set; }
    public string borderTopStyle { get; set; }
    public string borderTopWidth { get; set; }
    public string borderWidth { get; set; }
    public string bottom { get; set; }
    public string boxShadow { get; set; }
    public string boxSizing { get; set; }
    public string breakAfter { get; set; }
    public string breakBefore { get; set; }
    public string breakInside { get; set; }
    public string bufferedRendering { get; set; }
    public string captionSide { get; set; }
    public string caretColor { get; set; }
    public string clear { get; set; }
    public string clip { get; set; }
    public string clipPath { get; set; }
    public string clipRule { get; set; }
    public string color { get; set; }
    public string colorInterpolation { get; set; }
    public string colorInterpolationFilters { get; set; }
    public string colorRendering { get; set; }
    public string colorScheme { get; set; }
    public string columnCount { get; set; }
    public string columnFill { get; set; }
    public string columnGap { get; set; }
    public string columnRule { get; set; }
    public string columnRuleColor { get; set; }
    public string columnRuleStyle { get; set; }
    public string columnRuleWidth { get; set; }
    public string columnSpan { get; set; }
    public string columnWidth { get; set; }
    public string columns { get; set; }
    public string contain { get; set; }
    public string containIntrinsicBlockSize { get; set; }
    public string containIntrinsicHeight { get; set; }
    public string containIntrinsicInlineSize { get; set; }
    public string containIntrinsicSize { get; set; }
    public string containIntrinsicWidth { get; set; }
    public string container { get; set; }
    public string containerName { get; set; }
    public string containerType { get; set; }
    public string content { get; set; }
    public string contentVisibility { get; set; }
    public string counterIncrement { get; set; }
    public string counterReset { get; set; }
    public string counterSet { get; set; }
    public string cursor { get; set; }
    public string cx { get; set; }
    public string cy { get; set; }
    public string d { get; set; }
    public string descentOverride { get; set; }
    public string direction { get; set; }
    public string display { get; set; }
    public string dominantBaseline { get; set; }
    public string emptyCells { get; set; }
    public string fallback { get; set; }
    public string fill { get; set; }
    public string fillOpacity { get; set; }
    public string fillRule { get; set; }
    public string filter { get; set; }
    public string flex { get; set; }
    public string flexBasis { get; set; }
    public string flexDirection { get; set; }
    public string flexFlow { get; set; }
    public string flexGrow { get; set; }
    public string flexShrink { get; set; }
    public string flexWrap { get; set; }
    public string @float { get; set; }
    public string floodColor { get; set; }
    public string floodOpacity { get; set; }
    public string font { get; set; }
    public string fontDisplay { get; set; }
    public string fontFamily { get; set; }
    public string fontFeatureSettings { get; set; }
    public string fontKerning { get; set; }
    public string fontOpticalSizing { get; set; }
    public string fontPalette { get; set; }
    public string fontSize { get; set; }
    public string fontStretch { get; set; }
    public string fontStyle { get; set; }
    public string fontSynthesis { get; set; }
    public string fontSynthesisSmallCaps { get; set; }
    public string fontSynthesisStyle { get; set; }
    public string fontSynthesisWeight { get; set; }
    public string fontVariant { get; set; }
    public string fontVariantAlternates { get; set; }
    public string fontVariantCaps { get; set; }
    public string fontVariantEastAsian { get; set; }
    public string fontVariantLigatures { get; set; }
    public string fontVariantNumeric { get; set; }
    public string fontVariantPosition { get; set; }
    public string fontVariationSettings { get; set; }
    public string fontWeight { get; set; }
    public string forcedColorAdjust { get; set; }
    public string gap { get; set; }
    public string grid { get; set; }
    public string gridArea { get; set; }
    public string gridAutoColumns { get; set; }
    public string gridAutoFlow { get; set; }
    public string gridAutoRows { get; set; }
    public string gridColumn { get; set; }
    public string gridColumnEnd { get; set; }
    public string gridColumnGap { get; set; }
    public string gridColumnStart { get; set; }
    public string gridGap { get; set; }
    public string gridRow { get; set; }
    public string gridRowEnd { get; set; }
    public string gridRowGap { get; set; }
    public string gridRowStart { get; set; }
    public string gridTemplate { get; set; }
    public string gridTemplateAreas { get; set; }
    public string gridTemplateColumns { get; set; }
    public string gridTemplateRows { get; set; }
    public string height { get; set; }
    public string hyphenateCharacter { get; set; }
    public string hyphenateLimitChars { get; set; }
    public string hyphens { get; set; }
    public string imageOrientation { get; set; }
    public string imageRendering { get; set; }
    public string inherits { get; set; }
    public string initialLetter { get; set; }
    public string initialValue { get; set; }
    public string inlineSize { get; set; }
    public string inset { get; set; }
    public string insetBlock { get; set; }
    public string insetBlockEnd { get; set; }
    public string insetBlockStart { get; set; }
    public string insetInline { get; set; }
    public string insetInlineEnd { get; set; }
    public string insetInlineStart { get; set; }
    public string isolation { get; set; }
    public string justifyContent { get; set; }
    public string justifyItems { get; set; }
    public string justifySelf { get; set; }
    public string left { get; set; }
    public string letterSpacing { get; set; }
    public string lightingColor { get; set; }
    public string lineBreak { get; set; }
    public string lineGapOverride { get; set; }
    public string lineHeight { get; set; }
    public string listStyle { get; set; }
    public string listStyleImage { get; set; }
    public string listStylePosition { get; set; }
    public string listStyleType { get; set; }
    public string margin { get; set; }
    public string marginBlock { get; set; }
    public string marginBlockEnd { get; set; }
    public string marginBlockStart { get; set; }
    public string marginBottom { get; set; }
    public string marginInline { get; set; }
    public string marginInlineEnd { get; set; }
    public string marginInlineStart { get; set; }
    public string marginLeft { get; set; }
    public string marginRight { get; set; }
    public string marginTop { get; set; }
    public string marker { get; set; }
    public string markerEnd { get; set; }
    public string markerMid { get; set; }
    public string markerStart { get; set; }
    public string mask { get; set; }
    public string maskType { get; set; }
    public string mathDepth { get; set; }
    public string mathShift { get; set; }
    public string mathStyle { get; set; }
    public string maxBlockSize { get; set; }
    public string maxHeight { get; set; }
    public string maxInlineSize { get; set; }
    public string maxWidth { get; set; }
    public string minBlockSize { get; set; }
    public string minHeight { get; set; }
    public string minInlineSize { get; set; }
    public string minWidth { get; set; }
    public string mixBlendMode { get; set; }
    public string negative { get; set; }
    public string objectFit { get; set; }
    public string objectPosition { get; set; }
    public string objectViewBox { get; set; }
    public string offset { get; set; }
    public string offsetAnchor { get; set; }
    public string offsetDistance { get; set; }
    public string offsetPath { get; set; }
    public string offsetPosition { get; set; }
    public string offsetRotate { get; set; }
    public string opacity { get; set; }
    public string order { get; set; }
    public string orphans { get; set; }
    public string outline { get; set; }
    public string outlineColor { get; set; }
    public string outlineOffset { get; set; }
    public string outlineStyle { get; set; }
    public string outlineWidth { get; set; }
    public string overflow { get; set; }
    public string overflowAnchor { get; set; }
    public string overflowClipMargin { get; set; }
    public string overflowWrap { get; set; }
    public string overflowX { get; set; }
    public string overflowY { get; set; }
    public string overlay { get; set; }
    public string overrideColors { get; set; }
    public string overscrollBehavior { get; set; }
    public string overscrollBehaviorBlock { get; set; }
    public string overscrollBehaviorInline { get; set; }
    public string overscrollBehaviorX { get; set; }
    public string overscrollBehaviorY { get; set; }
    public string pad { get; set; }
    public string padding { get; set; }
    public string paddingBlock { get; set; }
    public string paddingBlockEnd { get; set; }
    public string paddingBlockStart { get; set; }
    public string paddingBottom { get; set; }
    public string paddingInline { get; set; }
    public string paddingInlineEnd { get; set; }
    public string paddingInlineStart { get; set; }
    public string paddingLeft { get; set; }
    public string paddingRight { get; set; }
    public string paddingTop { get; set; }
    public string page { get; set; }
    public string pageBreakAfter { get; set; }
    public string pageBreakBefore { get; set; }
    public string pageBreakInside { get; set; }
    public string pageOrientation { get; set; }
    public string paintOrder { get; set; }
    public string perspective { get; set; }
    public string perspectiveOrigin { get; set; }
    public string placeContent { get; set; }
    public string placeItems { get; set; }
    public string placeSelf { get; set; }
    public string pointerEvents { get; set; }
    public string position { get; set; }
    public string prefix { get; set; }
    public string quotes { get; set; }
    public string r { get; set; }
    public string range { get; set; }
    public string resize { get; set; }
    public string right { get; set; }
    public string rotate { get; set; }
    public string rowGap { get; set; }
    public string rubyPosition { get; set; }
    public string rx { get; set; }
    public string ry { get; set; }
    public string scale { get; set; }
    public string scrollBehavior { get; set; }
    public string scrollMargin { get; set; }
    public string scrollMarginBlock { get; set; }
    public string scrollMarginBlockEnd { get; set; }
    public string scrollMarginBlockStart { get; set; }
    public string scrollMarginBottom { get; set; }
    public string scrollMarginInline { get; set; }
    public string scrollMarginInlineEnd { get; set; }
    public string scrollMarginInlineStart { get; set; }
    public string scrollMarginLeft { get; set; }
    public string scrollMarginRight { get; set; }
    public string scrollMarginTop { get; set; }
    public string scrollPadding { get; set; }
    public string scrollPaddingBlock { get; set; }
    public string scrollPaddingBlockEnd { get; set; }
    public string scrollPaddingBlockStart { get; set; }
    public string scrollPaddingBottom { get; set; }
    public string scrollPaddingInline { get; set; }
    public string scrollPaddingInlineEnd { get; set; }
    public string scrollPaddingInlineStart { get; set; }
    public string scrollPaddingLeft { get; set; }
    public string scrollPaddingRight { get; set; }
    public string scrollPaddingTop { get; set; }
    public string scrollSnapAlign { get; set; }
    public string scrollSnapStop { get; set; }
    public string scrollSnapType { get; set; }
    public string scrollTimeline { get; set; }
    public string scrollTimelineAxis { get; set; }
    public string scrollTimelineName { get; set; }
    public string scrollbarGutter { get; set; }
    public string shapeImageThreshold { get; set; }
    public string shapeMargin { get; set; }
    public string shapeOutside { get; set; }
    public string shapeRendering { get; set; }
    public string size { get; set; }
    public string sizeAdjust { get; set; }
    public string speak { get; set; }
    public string speakAs { get; set; }
    public string src { get; set; }
    public string stopColor { get; set; }
    public string stopOpacity { get; set; }
    public string stroke { get; set; }
    public string strokeDasharray { get; set; }
    public string strokeDashoffset { get; set; }
    public string strokeLinecap { get; set; }
    public string strokeLinejoin { get; set; }
    public string strokeMiterlimit { get; set; }
    public string strokeOpacity { get; set; }
    public string strokeWidth { get; set; }
    public string suffix { get; set; }
    public string symbols { get; set; }
    public string syntax { get; set; }
    public string system { get; set; }
    public string tabSize { get; set; }
    public string tableLayout { get; set; }
    public string textAlign { get; set; }
    public string textAlignLast { get; set; }
    public string textAnchor { get; set; }
    public string textCombineHorizontal { get; set; }
    public string textCombineUpright { get; set; }
    public string textDecoration { get; set; }
    public string textDecorationColor { get; set; }
    public string textDecorationLine { get; set; }
    public string textDecorationSkipInk { get; set; }
    public string textDecorationStyle { get; set; }
    public string textDecorationThickness { get; set; }
    public string textEmphasis { get; set; }
    public string textEmphasisColor { get; set; }
    public string textEmphasisPosition { get; set; }
    public string textEmphasisStyle { get; set; }
    public string textIndent { get; set; }
    public string textOrientation { get; set; }
    public string textOverflow { get; set; }
    public string textRendering { get; set; }
    public string textShadow { get; set; }
    public string textSizeAdjust { get; set; }
    public string textTransform { get; set; }
    public string textUnderlineOffset { get; set; }
    public string textUnderlinePosition { get; set; }
    public string textWrap { get; set; }
    public string timelineScope { get; set; }
    public string top { get; set; }
    public string touchAction { get; set; }
    public string transform { get; set; }
    public string transformBox { get; set; }
    public string transformOrigin { get; set; }
    public string transformStyle { get; set; }
    public string transition { get; set; }
    public string transitionBehavior { get; set; }
    public string transitionDelay { get; set; }
    public string transitionDuration { get; set; }
    public string transitionProperty { get; set; }
    public string transitionTimingFunction { get; set; }
    public string translate { get; set; }
    public string unicodeBidi { get; set; }
    public string unicodeRange { get; set; }
    public string userSelect { get; set; }
    public string vectorEffect { get; set; }
    public string verticalAlign { get; set; }
    public string viewTimeline { get; set; }
    public string viewTimelineAxis { get; set; }
    public string viewTimelineInset { get; set; }
    public string viewTimelineName { get; set; }
    public string viewTransitionName { get; set; }
    public string visibility { get; set; }
    public string webkitAlignContent { get; set; }
    public string webkitAlignItems { get; set; }
    public string webkitAlignSelf { get; set; }
    public string webkitAnimation { get; set; }
    public string webkitAnimationDelay { get; set; }
    public string webkitAnimationDirection { get; set; }
    public string webkitAnimationDuration { get; set; }
    public string webkitAnimationFillMode { get; set; }
    public string webkitAnimationIterationCount { get; set; }
    public string webkitAnimationName { get; set; }
    public string webkitAnimationPlayState { get; set; }
    public string webkitAnimationTimingFunction { get; set; }
    public string webkitAppRegion { get; set; }
    public string webkitAppearance { get; set; }
    public string webkitBackfaceVisibility { get; set; }
    public string webkitBackgroundClip { get; set; }
    public string webkitBackgroundOrigin { get; set; }
    public string webkitBackgroundSize { get; set; }
    public string webkitBorderAfter { get; set; }
    public string webkitBorderAfterColor { get; set; }
    public string webkitBorderAfterStyle { get; set; }
    public string webkitBorderAfterWidth { get; set; }
    public string webkitBorderBefore { get; set; }
    public string webkitBorderBeforeColor { get; set; }
    public string webkitBorderBeforeStyle { get; set; }
    public string webkitBorderBeforeWidth { get; set; }
    public string webkitBorderBottomLeftRadius { get; set; }
    public string webkitBorderBottomRightRadius { get; set; }
    public string webkitBorderEnd { get; set; }
    public string webkitBorderEndColor { get; set; }
    public string webkitBorderEndStyle { get; set; }
    public string webkitBorderEndWidth { get; set; }
    public string webkitBorderHorizontalSpacing { get; set; }
    public string webkitBorderImage { get; set; }
    public string webkitBorderRadius { get; set; }
    public string webkitBorderStart { get; set; }
    public string webkitBorderStartColor { get; set; }
    public string webkitBorderStartStyle { get; set; }
    public string webkitBorderStartWidth { get; set; }
    public string webkitBorderTopLeftRadius { get; set; }
    public string webkitBorderTopRightRadius { get; set; }
    public string webkitBorderVerticalSpacing { get; set; }
    public string webkitBoxAlign { get; set; }
    public string webkitBoxDecorationBreak { get; set; }
    public string webkitBoxDirection { get; set; }
    public string webkitBoxFlex { get; set; }
    public string webkitBoxOrdinalGroup { get; set; }
    public string webkitBoxOrient { get; set; }
    public string webkitBoxPack { get; set; }
    public string webkitBoxReflect { get; set; }
    public string webkitBoxShadow { get; set; }
    public string webkitBoxSizing { get; set; }
    public string webkitClipPath { get; set; }
    public string webkitColumnBreakAfter { get; set; }
    public string webkitColumnBreakBefore { get; set; }
    public string webkitColumnBreakInside { get; set; }
    public string webkitColumnCount { get; set; }
    public string webkitColumnGap { get; set; }
    public string webkitColumnRule { get; set; }
    public string webkitColumnRuleColor { get; set; }
    public string webkitColumnRuleStyle { get; set; }
    public string webkitColumnRuleWidth { get; set; }
    public string webkitColumnSpan { get; set; }
    public string webkitColumnWidth { get; set; }
    public string webkitColumns { get; set; }
    public string webkitFilter { get; set; }
    public string webkitFlex { get; set; }
    public string webkitFlexBasis { get; set; }
    public string webkitFlexDirection { get; set; }
    public string webkitFlexFlow { get; set; }
    public string webkitFlexGrow { get; set; }
    public string webkitFlexShrink { get; set; }
    public string webkitFlexWrap { get; set; }
    public string webkitFontFeatureSettings { get; set; }
    public string webkitFontSmoothing { get; set; }
    public string webkitHyphenateCharacter { get; set; }
    public string webkitJustifyContent { get; set; }
    public string webkitLineBreak { get; set; }
    public string webkitLineClamp { get; set; }
    public string webkitLocale { get; set; }
    public string webkitLogicalHeight { get; set; }
    public string webkitLogicalWidth { get; set; }
    public string webkitMarginAfter { get; set; }
    public string webkitMarginBefore { get; set; }
    public string webkitMarginEnd { get; set; }
    public string webkitMarginStart { get; set; }
    public string webkitMask { get; set; }
    public string webkitMaskBoxImage { get; set; }
    public string webkitMaskBoxImageOutset { get; set; }
    public string webkitMaskBoxImageRepeat { get; set; }
    public string webkitMaskBoxImageSlice { get; set; }
    public string webkitMaskBoxImageSource { get; set; }
    public string webkitMaskBoxImageWidth { get; set; }
    public string webkitMaskClip { get; set; }
    public string webkitMaskComposite { get; set; }
    public string webkitMaskImage { get; set; }
    public string webkitMaskOrigin { get; set; }
    public string webkitMaskPosition { get; set; }
    public string webkitMaskPositionX { get; set; }
    public string webkitMaskPositionY { get; set; }
    public string webkitMaskRepeat { get; set; }
    public string webkitMaskRepeatX { get; set; }
    public string webkitMaskRepeatY { get; set; }
    public string webkitMaskSize { get; set; }
    public string webkitMaxLogicalHeight { get; set; }
    public string webkitMaxLogicalWidth { get; set; }
    public string webkitMinLogicalHeight { get; set; }
    public string webkitMinLogicalWidth { get; set; }
    public string webkitOpacity { get; set; }
    public string webkitOrder { get; set; }
    public string webkitPaddingAfter { get; set; }
    public string webkitPaddingBefore { get; set; }
    public string webkitPaddingEnd { get; set; }
    public string webkitPaddingStart { get; set; }
    public string webkitPerspective { get; set; }
    public string webkitPerspectiveOrigin { get; set; }
    public string webkitPerspectiveOriginX { get; set; }
    public string webkitPerspectiveOriginY { get; set; }
    public string webkitPrintColorAdjust { get; set; }
    public string webkitRtlOrdering { get; set; }
    public string webkitRubyPosition { get; set; }
    public string webkitShapeImageThreshold { get; set; }
    public string webkitShapeMargin { get; set; }
    public string webkitShapeOutside { get; set; }
    public string webkitTapHighlightColor { get; set; }
    public string webkitTextCombine { get; set; }
    public string webkitTextDecorationsInEffect { get; set; }
    public string webkitTextEmphasis { get; set; }
    public string webkitTextEmphasisColor { get; set; }
    public string webkitTextEmphasisPosition { get; set; }
    public string webkitTextEmphasisStyle { get; set; }
    public string webkitTextFillColor { get; set; }
    public string webkitTextOrientation { get; set; }
    public string webkitTextSecurity { get; set; }
    public string webkitTextSizeAdjust { get; set; }
    public string webkitTextStroke { get; set; }
    public string webkitTextStrokeColor { get; set; }
    public string webkitTextStrokeWidth { get; set; }
    public string webkitTransform { get; set; }
    public string webkitTransformOrigin { get; set; }
    public string webkitTransformOriginX { get; set; }
    public string webkitTransformOriginY { get; set; }
    public string webkitTransformOriginZ { get; set; }
    public string webkitTransformStyle { get; set; }
    public string webkitTransition { get; set; }
    public string webkitTransitionDelay { get; set; }
    public string webkitTransitionDuration { get; set; }
    public string webkitTransitionProperty { get; set; }
    public string webkitTransitionTimingFunction { get; set; }
    public string webkitUserDrag { get; set; }
    public string webkitUserModify { get; set; }
    public string webkitUserSelect { get; set; }
    public string webkitWritingMode { get; set; }
    public string whiteSpace { get; set; }
    public string whiteSpaceCollapse { get; set; }
    public string widows { get; set; }
    public string width { get; set; }
    public string willChange { get; set; }
    public string wordBreak { get; set; }
    public string wordSpacing { get; set; }
    public string wordWrap { get; set; }
    public string writingMode { get; set; }
    public string x { get; set; }
    public string y { get; set; }
    public string zIndex { get; set; }
    public string zoom { get; set; }
    public string mozOsxFontSmoothing { get; set; }
    public string boxDecorationBreak { get; set; }
    public string cssFloat { get; set; }
    public string cssText { get; set; }
    public string fontLanguageOverride { get; set; }
    public string fontSizeAdjust { get; set; }
    public string gridAutoPosition { get; set; }
    public string icon { get; set; }
    public string imageResolution { get; set; }
    public string imeMode { get; set; }
    public string marks { get; set; }
    public string navDown { get; set; }
    public string navIndex { get; set; }
    public string navLeft { get; set; }
    public string navRight { get; set; }
    public string navUp { get; set; }
    public string overflowClipBox { get; set; }
}
