// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SvgViewer
{
    internal sealed partial class Vsix
    {
        public const string Id = "ComponentPreview.7a08d0d4-985c-4415-93d5-ddd9135d8f4f";
        public const string Name = "Json to React UI with CSharp - Component Preview";
        public const string Description = @"Live preview of React component in c# code.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Abdullah Beyaztaþ";
        public const string Tags = "react,c#";
    }
}
