namespace ReactWithDotNet.ThirdPartyLibraries.MUI.Material;

public interface IColorPalette
{
    string primary_50 { get; }
    string primary_100 { get; }
    string primary_200 { get; }
    string primary_300 { get; }
    string primary_400 { get; }
    string primary_500 { get; }
    string primary_600 { get; }
    string primary_700 { get; }
    string primary_800 { get; }
    string primary_900 { get; }
    string primary_main { get; }
    string primary_light { get; }
    string primary_dark { get; }
    string primary_contrastText { get; }
    string primary_mainChannel { get; }
    string primary_lightChannel { get; }
    string primary_darkChannel { get; }
    string primary_contrastTextChannel { get; }
    string divider { get; }
    string primaryDark_50 { get; }
    string primaryDark_100 { get; }
    string primaryDark_200 { get; }
    string primaryDark_300 { get; }
    string primaryDark_400 { get; }
    string primaryDark_500 { get; }
    string primaryDark_600 { get; }
    string primaryDark_700 { get; }
    string primaryDark_800 { get; }
    string primaryDark_900 { get; }
    string primaryDark_main { get; }
    string primaryDark_mainChannel { get; }
    string background_default { get; }
    string background_paper { get; }
    string background_defaultChannel { get; }
    string common_black { get; }
    string common_white { get; }
    string common_background { get; }
    string common_onBackground { get; }
    string common_backgroundChannel { get; }
    string common_onBackgroundChannel { get; }
    string text_primary { get; }
    string text_secondary { get; }
    string text_disabled { get; }
    //string text_icon { get; }
    string text_primaryChannel { get; }
    string text_secondaryChannel { get; }
    string grey_50 { get; }
    string grey_100 { get; }
    string grey_200 { get; }
    string grey_300 { get; }
    string grey_400 { get; }
    string grey_500 { get; }
    string grey_600 { get; }
    string grey_700 { get; }
    string grey_800 { get; }
    string grey_900 { get; }
    string grey_main { get; }
    string grey_contrastText { get; }
    string grey_A100 { get; }
    string grey_A200 { get; }
    string grey_A400 { get; }
    string grey_A700 { get; }
    string grey_mainChannel { get; }
    string grey_contrastTextChannel { get; }
    string error_50 { get; }
    string error_100 { get; }
    string error_200 { get; }
    string error_300 { get; }
    string error_400 { get; }
    string error_500 { get; }
    string error_600 { get; }
    string error_700 { get; }
    string error_800 { get; }
    string error_900 { get; }
    string error_main { get; }
    string error_light { get; }
    string error_dark { get; }
    string error_contrastText { get; }
    string error_mainChannel { get; }
    string error_lightChannel { get; }
    string error_darkChannel { get; }
    string error_contrastTextChannel { get; }
    string success_50 { get; }
    string success_100 { get; }
    string success_200 { get; }
    string success_300 { get; }
    string success_400 { get; }
    string success_500 { get; }
    string success_600 { get; }
    string success_700 { get; }
    string success_800 { get; }
    string success_900 { get; }
    string success_main { get; }
    string success_light { get; }
    string success_dark { get; }
    string success_contrastText { get; }
    string success_mainChannel { get; }
    string success_lightChannel { get; }
    string success_darkChannel { get; }
    string success_contrastTextChannel { get; }
    string warning_50 { get; }
    string warning_100 { get; }
    string warning_200 { get; }
    string warning_300 { get; }
    string warning_400 { get; }
    string warning_500 { get; }
    string warning_600 { get; }
    string warning_700 { get; }
    string warning_800 { get; }
    string warning_900 { get; }
    string warning_main { get; }
    string warning_light { get; }
    string warning_dark { get; }
    string warning_contrastText { get; }
    string warning_mainChannel { get; }
    string warning_lightChannel { get; }
    string warning_darkChannel { get; }
    string warning_contrastTextChannel { get; }
    string secondary_main { get; }
    string secondary_light { get; }
    string secondary_dark { get; }
    string secondary_contrastText { get; }
    string secondary_mainChannel { get; }
    string secondary_lightChannel { get; }
    string secondary_darkChannel { get; }
    string secondary_contrastTextChannel { get; }
    string info_main { get; }
    string info_light { get; }
    string info_dark { get; }
    string info_contrastText { get; }
    string info_mainChannel { get; }
    string info_lightChannel { get; }
    string info_darkChannel { get; }
    string info_contrastTextChannel { get; }
    string action_active { get; }
    string action_hover { get; }
    double action_hoverOpacity { get; }
    string action_selected { get; }
    double action_selectedOpacity { get; }
    string action_disabled { get; }
    string action_disabledBackground { get; }
    double action_disabledOpacity { get; }
    string action_focus { get; }
    double action_focusOpacity { get; }
    double action_activatedOpacity { get; }
    string action_activeChannel { get; }
    string action_selectedChannel { get; }
    string Alert_errorColor { get; }
    string Alert_infoColor { get; }
    string Alert_successColor { get; }
    string Alert_warningColor { get; }
    string Alert_errorFilledBg { get; }
    string Alert_infoFilledBg { get; }
    string Alert_successFilledBg { get; }
    string Alert_warningFilledBg { get; }
    string Alert_errorFilledColor { get; }
    string Alert_infoFilledColor { get; }
    string Alert_successFilledColor { get; }
    string Alert_warningFilledColor { get; }
    string Alert_errorStandardBg { get; }
    string Alert_infoStandardBg { get; }
    string Alert_successStandardBg { get; }
    string Alert_warningStandardBg { get; }
    string Alert_errorIconColor { get; }
    string Alert_infoIconColor { get; }
    string Alert_successIconColor { get; }
    string Alert_warningIconColor { get; }
    string AppBar_defaultBg { get; }
    //string AppBar_darkBg { get; }
    //string AppBar_darkColor { get; }
    string Avatar_defaultBg { get; }
    string Chip_defaultBorder { get; }
    string Chip_defaultAvatarColor { get; }
    string Chip_defaultIconColor { get; }
    string FilledInput_bg { get; }
    string FilledInput_hoverBg { get; }
    string FilledInput_disabledBg { get; }
    string LinearProgress_primaryBg { get; }
    string LinearProgress_secondaryBg { get; }
    string LinearProgress_errorBg { get; }
    string LinearProgress_infoBg { get; }
    string LinearProgress_successBg { get; }
    string LinearProgress_warningBg { get; }
    string Skeleton_bg { get; }
    string Slider_primaryTrack { get; }
    string Slider_secondaryTrack { get; }
    string Slider_errorTrack { get; }
    string Slider_infoTrack { get; }
    string Slider_successTrack { get; }
    string Slider_warningTrack { get; }
    string SnackbarContent_bg { get; }
    string SnackbarContent_color { get; }
    string SpeedDialAction_fabHoverBg { get; }
    string StepConnector_border { get; }
    string StepContent_border { get; }
    string Switch_defaultColor { get; }
    string Switch_defaultDisabledColor { get; }
    string Switch_primaryDisabledColor { get; }
    string Switch_secondaryDisabledColor { get; }
    string Switch_errorDisabledColor { get; }
    string Switch_infoDisabledColor { get; }
    string Switch_successDisabledColor { get; }
    string Switch_warningDisabledColor { get; }
    string TableCell_border { get; }
    string Tooltip_bg { get; }
    string dividerChannel { get; }
    double opacity_inputPlaceholder { get; }
    double opacity_inputUnderline { get; }
    double opacity_switchTrackDisabled { get; }
    double opacity_switchTrack { get; }
}