namespace QuranAnalyzer.WebUI.Pages;

public class IsHeMessangerPage : ReactComponent
{
    protected override Element render()
    {
        return new Article
        {
            new LargeTitle("Reşad Halife peygamberliğini ilan etmiş doğru mu?"),

            new div
            {
             innerHTML   = @"

   <h3 style=""text-align:center;"">Reşad Halife peygamberliğini ilan etmiş doğru mu?</h3>
<p>Bu yazıda farklı farklı konuların sadece satırbaşlarını ele alabildim.<br>Lütfen bu yazıdaki hiçbir bilgiyi peşinen doğru kabul etmeyin.<br>Bu konuları araştırmak ve üzerine derin derin düşünmeniz sizin sorumluluğunuzdadır.</p>
<p>Öncelikle lafı hiç dolandırmadan cevabını verelim.<br>Reşad Halife hiçbir zaman <strong>peygamberim dememiştir</strong>.&nbsp;<br>Net bir şekilde <strong>elçiyim demiştir.</strong></p>
<p>Arapçada nebi(peygamber) ve resul(elçi) diye iki kelime var. &nbsp;<br>Bir çok konuda olduğu gibi &nbsp;bu iki kelime üzerinde de tartışmalar yaşanmaktadır.&nbsp;<br>Burada karşıt fikirler şunlardır. Bir taraf diyor ki son peygamber de son elçi de Muhammed peygamberdir.&nbsp;<br>Buna delil olarak bazı rivayetler veriyorlar veya kelimenin köklerine inip biri kitap verilendir öteki haber veren demektir gibi, Nebi kavramı resul kavramını &nbsp;kapsar gibi uzun süren tartışmalar var.</p>
<p><br>Peki Kuran’da bu bilgi nasıl ele alınmış diye soracak olur isek elbette bu sefer de Kuran’daki yorum farkları devreye giriyor. O ayet onu kastetmiyor şunu kastediyor gibi yorumlar var.</p>
<p><br>Şunu net bir şekilde söyleyebiliriz.<br>Kuranda açık bir şekilde (Ahzab suresi 40.ayet) &nbsp;<strong>Muhammed’in bir resul olduğunu ve nebilerin sonuncusu</strong> olduğunu ifade eder.&nbsp;<br>Kurandan sonra başka kutsal yazı da inmeyeceği Kuranda açık bir şekilde ifade edilmiştir.</p>
<p><br>Özetle iki görüş var.<br>1.&nbsp;&nbsp;&nbsp;&nbsp;Görüş: Muhammed peygamberden sonra Resul(elçi) de Peygamber(nebii) de gelmeyecektir. Ayetleri bu mantığa göre yorumluyorlar. Nebilik elçiliği kapsar gibi bir anlam yükleyip elçiliğin de önünü kapatıyorlar.</p>
<p><br>2.&nbsp;&nbsp;&nbsp;&nbsp;Görüş: Kuranda Muhammed için resul ve peygamber kelimeleri ayrı kullanıldığına göre ve aynı zamanda son nebii dediğine göre demek ki başka resuller(elçiler) &nbsp;de gelebilir.<br>Gelen elçiler de yine Kuran üzerine amel edip dinin şirk bulaşan kısımları konusunda insanlara doğruyu göstermek durumundalar. Yahudilere bir çok resul gönderilmiş. Hepsine kitap verilmedi.<br>Hatta Kuranda net bir şekilde şu bilgi yer alır. İnsanlar Yusuf peygamberden sonra başka birinin gönderilmeyeceğini düşünmüşler. &nbsp;Yusuf suresini okursanız bu bilgiyi görebilirsiniz.&nbsp;<br>Halbuki Yusuf’ dan sonra Musa gibi, İsa gibi &nbsp;peygamberler gönderildi. Hatta Kurana bakarsanız 3:81 numaralı ayette tüm kutsal yazıları doğrulayan bir elçiden bahsediliyor.</p>
<p>Peki bu iki görüşten hangisi doğru?<br>Bu soru din ile ilgili bir soru.<br>Otomatikman şu soruyu sormanız lazım.&nbsp;<br>Peki <strong>dinin kaynağı nedir?</strong> Bu sorulara verilen cevapların doğru olup olmadığını neye göre bileceğim?<br>İşte bu sorunun cevabı da ikiye ayrılıyor.&nbsp;<br>1-&nbsp;&nbsp;&nbsp;&nbsp;Yalnız Kuran<br>2-&nbsp;&nbsp;&nbsp;&nbsp;Kuran + hadis + alimler + bizden önceki nesillerin yorumu</p>
<p>Sadece bir fikri değil her iki tarafın fikirlerini de <strong>önyargısız bir şekilde</strong> dinlemeli ve ona göre karar vermelisiniz.</p>
<p>Gelelim Reşad’ın elçilik meselesine. Bu konuya giriş mahiyetinde iki veri sunup konuyu daha farklı ele alacağım.</p>
<p>-&nbsp;&nbsp;&nbsp;&nbsp;Kuranda Reşad kelimesinin kök harfi olan <strong>RŞD kök harfi toplamda 19 kez</strong> geçer.</p>
<p>-&nbsp;&nbsp;&nbsp;&nbsp;Reşad Halife'nin doğum tarihi ve öldürülme tarihi net olarak bilinmektedir.&nbsp;</p>
<p>&nbsp; &nbsp; &nbsp;Toplamda bu dünyada 19,798 gün yaşamıştır. 19. Surede 798 adet başlangıç harfi vardır.</p>
<p>Bu örnek verdiğim iki bilgi gerçekten de çok şaşırtıcı. Bunun gibi başka daha bir çok bilgiyi internette kolayca bulabilirsiniz. Ben olayın mantığını anlatmaya çalışacağım.</p>
<p><br>Olayları bütüncül anlayabilmek için şimdi sizinle ufak bir zaman yolculuğuna çıkalım.</p>
<p>Milattan önceki yıllara gidelim. Musa adında biri var. &nbsp;Allah ile bizzat sesli konuştuğunu iddia ediyor. Bir an için kendinizi o zamanın toplumunda yaşayan biri olarak düşünün &nbsp;ve elinizi vicdanınıza koyun ve cevap verin.</p>
<p>Karşınızda duran herhangi biri Allah ile aracısız bir biçimde konuştuğunu söylese hangimiz ciddiye alırdık?</p>
<p><br>Devam edelim. Öyle bir toplum ki neredeyse her şey firavun &nbsp;ve etrafındakiler tarafından yönetiliyor.Haliyle verilen rızıkları sanki firavun sağlıyormuş gibi bir fikre kapılmış olan bir toplumdasınız. Ortalık sihirbaz dolu.<br>Musa adındaki bu adam size kupkuru çöle gidelim diyor. Derken asa yılanları yutuveriyor ortalık karışıyor Musa ile beraber Kızıldeniz’in ortasından geçiyorsunuz. Firavunun ve askerlerinin boğulduğunu bizzat görüyorsunuz.Ardından çölün ortasında bıldırcın eti ile nimetleniyorsunuz.</p>
<p>Tabii imtihan bitmiyor Musa diyor ki emir geldi şu şehre girin.Ama ölüm korkusu ağır basıyor ve Tevratda yazılana göre Musa’nın bu emrine sadece <strong>iki kişi</strong> gönülden uyuyor.</p>
<p>Aradan yüzyıllar geçiyor. Yahudiler Mesih bekleyişi içindeler. İlerde ufak insan kalabalığı var. O sırada oradan geçen biri olduğunuzu hayal edin. Çarmıha gerilmiş üç kişi var.&nbsp;<br>Etraftaki birine yanaşıp soruyorsunuz kim bunlar? suçları ne? cevap şöyle: İkisi hırsız, biri de meczubun biri garibim kendini mesih sanıyor, peygamber sanıyor bak işte şuradaki 10 fakir kişi de onun talebeleri.</p>
<p>İşte o kişi İsa peygamberdi.</p>
<p>&nbsp;</p>
<p>Aradan yüzyıllar geçiyor. Arabistan’ın çöllerine ışınlanıyoruz. Mekke sokaklarında Muhammed adında biri peygamber olduğunu söylüyor. Etraftaki bir tanıdığınıza soruyorsunuz bu adam nasıl vahiy alıyormuş? Cevap: rüyasında.(Hadis kaynaklarına bakarsanız ilk vahiyler rüya yoluyla geliyor.)</p>
<p>Tam burada durup şu soruyu sorun karşımdaki kişi bana peygamber olduğunu söylese ve nasıl olduğunu sorduğunuzda&nbsp;<br>rüyasında bu bilgilerin geldiğini söylese o adama karşı tutumunuz ne olurdu?</p>
<p>Aradan 11-12 yıl geçmiş bu adamın etrafına toplamda 300 kişi anca toplanmış.<br>(Bedir savaşında Müslümanların yaklaşık rakamı 300 civarındadır.)<br>Düşünün ki bir insan var 10 yıldan fazladır uğraşıyor ve etrafına sadece 300 kişi toplayabilmiş.<br>Çoğunluk onun tarafında değil. Siz o zamanda gelseydiniz çoğunluğun mu yanında olurdunuz yoksa o kişinin yanında mı olurdunuz?<br>Düşünün ki Bedir savaşına katılırsanız hem sizi öldürecekler hem de geride bıraktığınız ne varsa (mallarınız- eşiniz-kızınız) çökecekler.<br>İşte böyle bir durumda her şeyinizi geride bırakıp savaşa katılır mıydınız?</p>
<p>2 bin yıl sonrasına kendi zamanımıza geri geliyoruz.<br><strong>Paket bir din</strong>' i önceki nesillerden devralıyoruz.&nbsp;<br>Bu paketin içinde Kuran var, peygambere ait olduğu ileri sürülen sözler – emirler var, &nbsp;kendi milletinize ait bazı adet gelenek görenekler var. Eski alimlerin yahut mevcut siyasi otoritelerin bakış açılarına göre yorumlanmış bir karışım var. Mesela Türkiye’deki İslami anlayış ile İran’daki İslami anlayış birbirinden farklıdır.</p>
<ul>
    <li>Kuranda mescitlerde Allah’ın adı tek anılsın diye açık emir varken camilerde Allah lafzının yanına Muhammed lafzı yazılmayan camii yok gibi.</li>
    <li>İnsanlar &nbsp;ölmüş olan Muhammed peygamberin şefaat etmesi için camilerde toplu şekilde dua içinde ona sesleniyorlar.</li>
    <li>Kuranda zinanın suçu net olarak belirlenmişken Afganistan gibi bölgelerde kadınları toprağa gömüp taşlayarak öldürüyorlar.</li>
    
</ul>
İşte böyle bir zamanda Reşad adında biri çıkıp diyor ki ey Müslümanlar Kurana uyun. &nbsp;Ey insanlar! İsa’yı Muhammed’i tarikat liderlerini, azizleri putlaştırmaktan vazgeçin.
<p>Aslında buraya kadar anlatmak istediğim şey şu.<br>Kuranı okuyan herkes bilir ki Kuran’daki ana &nbsp;mesele <strong>tevhid - şirk</strong> meseledir.&nbsp;<br>Şirk ise zaten insanların uyanamadığı noktada olur. Merhametlilerin En Merhametlisi‘ de biz insanları uyandırmak için elçiler-kitaplar-peygamberler gönderir.&nbsp;<br>Zaten insanlar bir şeyin şirk olduğunu fark edebilse zaten yapmaz.</p>
<p>Elbette kumar-içki gibi günahlar da var, Allah isterse affeder istemezse affetmez.&nbsp;<br>Bir günah var ki Allah asla affetmem &nbsp;diyor. O da şirk, yani Allah’tan başkasına güç atfetmek.<br>İşte şeytan da tam bu noktadan insanları vurmalı ki kendince başarılı olabilsin.</p>
<p>Biz Müslümanlar olarak Hristiyanlara bakıp şöyle söylüyoruz şeytan sizleri İsa’nın &nbsp;Allah’ın oğlu olduğuna inandırmış yanlış yoldasınız diyoruz.&nbsp;<br>Halbuki bizim coğrafyadaki bir çok Müslüman tüm varlığın Muhammed peygamberin yüzü suyu hürmetine yaratıldığına inanıyor.&nbsp;<br>Acaba biz Müslümanlar da &nbsp;şeytanın başka bir oyununa gelmiş olmayalım?</p>
<p><br>Birazda olayı daha rasyonel ele alalım.</p>
<p>Eğer bir kişi ben elçiyim diyor ise;<br>1-&nbsp;&nbsp;&nbsp;&nbsp;Ya bu kişi yalancıdır menfaat için bilerek Allah adına yalan söylüyor.<br>2-&nbsp;&nbsp;&nbsp;&nbsp;Özünde çok iyi biridir ve akli olarak karışmıştır, mental rahatsızlığı vardır, şeytan bir şeyler fısıldamıştır ve kendisinin elçi olduğuna inanmıştır veya etrafındakiler inandırmıştır.<br>3-&nbsp;&nbsp;&nbsp;&nbsp;Bu kişi gerçekten elçidir.</p>
<p>Kuranda elçilerin <strong>ücret istemiyor</strong> olması, <strong>yalnızca tevhide</strong> çağırıyor olması özellikle vurgulanır. Hatta elçilere <strong>kanıtlar </strong>verildiğinden bahsedilir.&nbsp;<br>Mesela Kuranda Musa’ya 9 tane kanıt verildiğinden bahseder.</p>
<p>Şimdi gelelim Reşad’ın iddiasına;<br>Zaten 1980 den itibaren elçi olduğunu kendisi de biliyor.<br>Ama önemli olan insanları bu içinde bulundukları şirklerinden arındırmaktır diye düşünüyor.<br>Kendisinin de önceki elçiler gibi bir elçi olduğunu söylese insanlar kabul etmekte zorlanabilirler diye düşünüyor. O yüzden elçi olduğunu kimseye söyemiyor.<br>Elinden geldiğince aldığı mesajları aktarıyor.&nbsp;<br>Kamera karşısına geçiyor doğru namazın nasıl kılınacağı ile ilgili, evrim ile ilgili, video çekiyor, radyo programlarına katılıyor, seminerlere gidiyor.<br>Kuranın Allah kelamı olduğunu dünyaya ispatlamak için elinden geleni yapıyor.&nbsp;<br>1970’li yıllarda Kuranı bilgisayara aktarmak kimin aklına gelir ki!<br>Üstelik o yıllardaki bilgisayar teknolojisinde Arap alfabesi bile yok. Kim böyle bir iş için 3-4 yılını harcar.<br>Yıl 1988 olunca artık bunu söylemesi gerektiği ona dikte ediliyor. O da insanlara söylüyor.&nbsp;<br>Ölüm tehditleri almasına rağmen geri adım atmıyor. Zaten 2 yıl sonra da sabah namazında öldürülüyor.</p>
<p><br>Gelelim kanıt kısmına;<br><strong>İbn-i Sina</strong> gibi, <strong>İbn-i Arabi</strong> gibi, <strong>Gazali </strong>gibi, <strong>Bediüzzaman Said Nursi</strong> gibi bulunduğu zamanların dâhileri olan insanlar gelmiş geçmişler.&nbsp;<br>19 gibi çok basit bir örüntüyü Kuranda nasıl göremediler?&nbsp;<br>50. Sure Kaf(ق) harfi ile başlar ve toplamda 45 ayettir.&nbsp;<br>O kadar alim geldi geçti hiç mi birinin aklına gelmemiş bu suredeki Kaf(ق) harflerini saymak? 5 dakika bile sürmez.<br>İşte bizim düşünsel hatamız burada. <strong>Olayın zeka ile takva ile olduğunu sanıyoruz</strong>.&nbsp;<br>Şunu kabul etmemiz lazım <strong>1400 yıldır Kuranda var olan 19 örüntüsünü ilk Reşad gördü veya görmesine izin verildi.&nbsp;</strong><br>Unutmayalım ki Kuran’a sadece samimiler dokunabilirler.</p>
<p>&nbsp;</p>
<p>Peki 19 kanıt mı ?</p>
<p>Günümüz teknolojisi ile yapılan illüzyon gösterilerinden bahsetmeme gerek yok sanırım.<br>Önümüze hangi mucize konur ise konsun illüzyon deyip geçebilirdik. Suda yürüyenden tutun havada uçana kadar her türlü illüzyon var.<br>Haliyle Reşad’a verilen bu matematiksel mucize biraz daha anlam kazanıyor. &nbsp;Tamda matematiğin – bilimin- bilgisayarın patlama yaptığı bir çağda bu tarz bir mucizenin ortaya çıkması oldukça mantıklı.<br>Kuranda <strong>kanıt(beyyine) kelimesinin 19 kez</strong> geçtiğini söylememe gerek yok sanırım.</p>
<p>Maalesef günümüzde elinizi sallasanız ben peygamberim, ben elçiyim, ben mehdiyim, ben seçilmiş kişiyim diyene rastlarsınız. Herbirine vakit ayırsanız vaktiniz yetmez.&nbsp;<br>Tahminim o ki eski devirde de bu böyleydi. Anladığım kadarı ile <strong>En Bilge Olan</strong>'ın elçilerine - peygamberlerine o zamana uygun mucizeler vermesinin bir hikmeti de bu olabilir.&nbsp;<br>Sahte elçilerden ayırt etmek için onlara mucizeler-kanıtlar veriyor olabilir.<br>Eğer önceki elçilere verilenler gibi görsel bir mucize olsaydı bizler bugün canlı canlı göremezdik.&nbsp;<br>1400 yıldır o başlangıç harfleri Kuranda vardırlar. Kıyamete kadar da orada olmaya devam edecekler.<br>İnsanoğlu ahirette şöyle bir savunma yapamayacak.&nbsp;<br>Ey rabbim ben nerden bileyim hangi din doğru?&nbsp;<br>Herkes inanış kendi mahallesinde çok mutlu ve kendi inanıcının en doğru olduğunu savunuyordu. Her din kendi içinde mitolojileri vardı. Musa denizi yardığında ben orda değildim ben nerden bileyim gerçek mi? Uydurma mı?<br>İşte bu bahane insanların elinden alınmış oldu.&nbsp;<br>19 Mucizesi Kuranın Allah kelamı olduğunu doğruladı.&nbsp;<br>Kuran doğrulandığına göre Musa’nın İsa’nın birer peygamber olduğu doğrulanmış oldu.<br>Sonradan bazı bozulmalara uğramış olan Tevrat ve İncil’in Allah’tan geldiği doğrulanmış oldu.&nbsp;<br>İsa’nın ölüyü dirilttiği, Musa’nın Kızıldeniz’i yarmış olduğu ispatlanmış oldu.</p>
<p><br><strong>Eğer Reşad elçilerden biri ise neden bu bilgi Kuran’da açık bir şekilde yazılmadı?</strong><br>Sanırım Allah’ın sünneti bu şekilde işliyor.<br>Tevrat’a açık bir şekilde İsa’nın adını yazabilirdi ama yazmadı.&nbsp;<br>İncil’e açık bir şekilde Muhammed adını yazabilirdi ama yazmadı.<br>Elbette İncil’in ve Tevrat’ın içinde Muhammed peygambere işaretler olabilir. Bu biraz da nasıl yorumladığınıza bağlı. Sonuçta bugünün Hristiyanları İncilde Muhammed için bir işaret görmüyor. Görse zaten Müslüman olurlardı.</p>
<p>Zaten Kuranda sonraki gelecek elçiler açık bir şekilde isim soy isim verse herkes o ismi çocuklarına verirdi. Binde biri elçiyim dese ortalık elçiden geçilmezdi.</p>
<p><strong>Putlaştırma Hastalığımız.</strong><br>Sanırım biz insanoğlu olarak &nbsp;problemimiz şu;<br>Önce peygamberleri – elçileri öldürürüz yahut destek vermeyiz aradan zaman geçinde onları putlaştırırız. İsa peygamber örneğinde olduğu gibi.&nbsp;</p>
<p>Muhammed peygamber zamanında insanlar ona destek vermedi. 13 yıl geçmesine rağmen etrafına 300 adam toplayabildi.<br>Ama bugün ise Muhammed peygamberi öyle yüceltiyoruz ki sanki hep miraçta dolaşan biri olarak görüyoruz. &nbsp;<strong>Trilyonlarca Galaksiyi Avucunda Tutan</strong>’ın &nbsp;isminin yanına yazıyoruz.<br>Hatta bu sadece din adamları ile sınırlı da değil. &nbsp;<strong>Siyasi liderleri, tarikat-cemaat liderlerini, aşiretimizi, vatanımızı, bazen kendimizi bazen de evladımızı putlaştırıyoruz</strong>. Maalesef böyle.</p>
<p><br><strong>Peki Reşad sadece 19 dan mı bahsetti?</strong><br>Önce bugün yaşanan sorunu ele alalım.&nbsp;<br>Yalnız kuran deseniz dahi bu sefer <strong>yorum farkı</strong> ortaya çıkıyor.<br>Hadis temelli yapılan Kuran çevirileri ile, tarikat mensubu insanların yazdıkları çeviriler birbirinden çok farklı.<br>Son 30-40 yılda Türkiye’de kaç tane meal yazıldı sayısını tahmin bile edemiyorum.&nbsp;<br>Üstelik şu da bir gerçek hangi dil olur ise olsun bir metni bir dilden başka bir dile çeviriyorsanız orijinal dildeki tadı/ahengi tam aktaramazsınız.&nbsp;<br>Üstelik bugünün Arapçası ile 1400 yıl önceki Arapça arasında bile farklar var.<br>Özetle bugün tüm din meselesini Kuran ile sınırlandırsanız bile iş bitmiyor. Hangi kuran?</p>
<p>Tarikatlar Kuranı farklı yorumluyor, Diyanet farklı yorumluyor, Nurcular farklı yorumluyor.<br>Hepsi de samimi şekilde elinden geleni yapıyorlar. Ama bu bir realite. Aralarında yorum farkı var. bu yorum farkı çevrilere yansıyor. Bunun olması da normal.<br>Meseleyi sadece Türkiye ekseninde düşünmeyin. Mesele bu yaşadığımız zamanın genel bir sorunu.</p>
<p>Hatta Kuranda şöyle ifadeler var.&nbsp;<br>Eğer bu Kuran’ı başka bir dilde indirseydik onun anlaşılmayacağını ifade eden sözler var.<br>Bu durumda ben de Türkiye’de yaşayan biri olarak Arapçayı anlamıyorum.&nbsp;<br>Herkesten Arapça öğrenmesini de bekleyemezsiniz.&nbsp;<br><strong>Dolayısı ile Kuranın başka dillere çevirisi mecburi bir durumdur.</strong></p>
<p><br>İşin içine çeviri girince bu sefer de yorum farkı giriyor. &nbsp;<br>Hatta bu din meselesinin içine hadisleri de katarsak bu yelpazenin daha büyüğünü hayal edin.<br>Allah’ın muradını öğrenmek için bir sürü hadis-meal-tefsir-fıkıh kitapları okumanız gerekiyor demektir. Sanırım problemi anlatabilmişimdir.</p>
<p><br>Daha önce söylemiştim.&nbsp;<br>Reşad, Kuran'ı Arapçasından İngilizce diline çeviriyor. Arapça zaten anadili olduğu halde çeviri işi yaklaşık 20 yıl sürüyor.<br>Ve bu çevirinin adına <strong>Yetkilendirilmiş Çeviri</strong> diye bir isim veriyor.<br>Şunu iddia ediyor. Bu çeviri <strong>Tahtın Sahibi tarafından yetkilendirilmiş bir çeviridir</strong> diyor.<br>Bunu kenarda köşede kısık sesle söylemiyor.&nbsp;<br>Katıldığı konferanslarda Cuma hutbelerinde üzerine basa basa tekrarlıyor.</p>
<p><br>Mesela<br>... biz seni alemlere rahmet olarak gönderdik…<br>diye çevrilen yeri şöyle çeviriyor.<br>... biz seni alemlere olan rahmetimizden dolayı gönderdik…</p>
<p><br>Yaptığı çevride gücü-otoriteyi tümüyle Allaha atfeden tevhid merkezli bir anlayış içinde yapıyor.<br>Reşad’ı elçi olarak kabul etmeseniz bile Kuran çevrilerinde takıldığınızda bir yer olur ise onun çevirisine bakarak karşılaştırma yapmanızı öneririm.<br>Bin yılın tartışmalı konularını bir de onun Kuran merkezli izahları ile dinlemenizi öneririm.</p>
<p>Özetle Reşad<strong> sadece kuran</strong> diyor ve bunun altını dolduruyor.</p>
<p><br><strong>Kurandaki Hikayeler</strong><br>""Nede olsa Muhammed peygamberden sonra biri gelmeyecek.&nbsp;<br>Zaten kelime-i şehadet getiren &nbsp;her bir Müslüman cehenneme girse bile eninde sonunda cennete girecek.""<br>Eğer siz de eskiden benim düşündüğüm gibi hala böyle düşünüyor iseniz size kötü bir haberim var.<br>Allah’ın net bir biçimde affetmeyeceğini söylediği hata şirk hatasıdır. Kuran ise inananların bile çoğunun bu hataya düşeceğini haber veriyor. Müslüman da olsanız cennete gidemeyebilirsiniz.</p>
<p><br>Kuranda peygamberler kıssalarından çokça bahsedilir. Hatta aynı kıssayı farklı farklı tonlarda farklı yönleriyle bahseder. Hep bir uyarı alan toplumlar ve ardından üzerlerine azap gelen toplumlar.</p>
<p>Elbette Kuranda bir şeyin bahsi geçiyor ise mutlaka bir hikmeti vardır. Bizler Müslüman olduğumuza göre bu azapla vurulan kavimlerin başına gelenler bizim başımıza gelmeyecek diye düşünebiliriz. Hatta bu kafa yapısı ile yani ben zaten inanan bir insanım dolayısı ile inanmayanlara hitap eden şu ayetler bana hitap etmiyor kafası ile okuyabilirsiniz. Dolayısı ile kuranın yarısından fazlasını kenara koymanız lazım. Çünkü inanmayanları muhatap alan ayetleri birinci dereceden muhatap gibi algılayamazsınız çünkü inanan bir insansınız. Bunu isteseniz de yapamazsınız.</p>
<p><br>Gelin görün ki Kuranda klasik nerdeyse bir çok peygamber kıssasında yaşanan durumun tam da ortasındayız. Önce uyarıcılar gönderiyor ardından uymadıkları için azap geliyor.</p>
<p>Reşad &nbsp;bizzat Cebrail’den bu bilgiyi aldığını &nbsp;<strong>Arapları vuracak bir azabın haberini</strong> de veriyor ardından Kuranda bahsi geçen <strong>duman azabının </strong>yaşanacağını haber veriyor. Asıl dine dönüşün bu duman olayından sonra olacağını haber veriyor.</p>
<p><strong>Özetlersek;&nbsp;</strong><br>Kurana baktığımızda anlıyoruz ki aslında gönderilen bütün peygamberler-elçiler hep aynı mesajı seslendirmişler.<strong> Allah’tan başka Allah yoktur</strong>. Dini ritüellerde farklılıklar var. Ama mesajın özü hep aynı.<br><strong>Bir doğru üzerindeki noktalar</strong> gibi düşünebilirsiniz. Yol tevhid yolu.<br>Peygamberler, elçiler kocaman bir dağın yamacında bulunan çeşmenin başındaki musluklar gibilerdir.&nbsp;<br>Akan suyu da vahiy – hikmet - tevhid olarak kabul edersek, evet su musluktan damlıyor ama şunu kesin kez bilmeliyiz ki su musluğun kendisinden değil o kocaman dağdan akıp geliyor.</p>
<p>&nbsp;<br>Peygamberlerin – elçilerin kesinlikle hiç bir güçleri yoktur. &nbsp;Ne Nuh oğluna yardım edebildi, &nbsp;ne de İbrahim babasına yardım edebildi, tüm güç sadece Allah’a aittir.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>



"
            },

        };
    }
}